use crate::runtime::cli::OverlayLanguage;

#[derive(Debug, Clone, Copy)]
pub(crate) struct OverlayText {
    pub(crate) drag_hint: &'static str,
    pub(crate) toolbar_hint: &'static str,
    pub(crate) pin_action: &'static str,
    pub(crate) ocr_action: &'static str,
    pub(crate) close_ocr_action: &'static str,
    pub(crate) rerun_ocr_action: &'static str,
    pub(crate) translate_action: &'static str,
    pub(crate) close_action: &'static str,
    pub(crate) copy_action: &'static str,
    pub(crate) copy_image_action: &'static str,
    pub(crate) copy_selected_text_action: &'static str,
    pub(crate) copy_all_text_action: &'static str,
    pub(crate) save_action: &'static str,
    pub(crate) save_image_action: &'static str,
    pub(crate) capturing: &'static str,
    pub(crate) missing_snapshot: &'static str,
    pub(crate) missing_pin_image: &'static str,
    pub(crate) snapshot_load_failed: &'static str,
    pub(crate) pin_load_failed: &'static str,
    pub(crate) crop_failed: &'static str,
    pub(crate) copy_failed: &'static str,
    pub(crate) save_failed: &'static str,
    pub(crate) pin_spawn_failed: &'static str,
    pub(crate) capture_title: &'static str,
}

impl OverlayText {
    pub(crate) fn new(language: OverlayLanguage) -> Self {
        match language {
            OverlayLanguage::En => Self {
                drag_hint: "Drag to select a region",
                toolbar_hint: "Drag edges to adjust",
                pin_action: "Pin",
                ocr_action: "OCR",
                close_ocr_action: "Hide OCR",
                rerun_ocr_action: "OCR again",
                translate_action: "Translate",
                close_action: "Close",
                copy_action: "Copy",
                copy_image_action: "Copy image",
                copy_selected_text_action: "Copy selected text",
                copy_all_text_action: "Copy all text",
                save_action: "Save",
                save_image_action: "Save image",
                capturing: "Capturing...",
                missing_snapshot: "Missing screenshot snapshot",
                missing_pin_image: "Missing pinned image path",
                snapshot_load_failed: "Failed to load screenshot snapshot",
                pin_load_failed: "Failed to load pinned image",
                crop_failed: "Failed to save selected region",
                copy_failed: "Failed to copy selected region",
                save_failed: "Failed to save selected region",
                pin_spawn_failed: "Failed to open pin window",
                capture_title: "snap pin capture",
            },
            OverlayLanguage::Ja => Self {
                drag_hint: "ドラッグして範囲を選択",
                toolbar_hint: "端をドラッグして調整",
                pin_action: "ピン留め",
                ocr_action: "OCR",
                close_ocr_action: "OCR を非表示",
                rerun_ocr_action: "再 OCR",
                translate_action: "翻訳",
                close_action: "閉じる",
                copy_action: "コピー",
                copy_image_action: "画像をコピー",
                copy_selected_text_action: "選択テキストをコピー",
                copy_all_text_action: "全文をコピー",
                save_action: "保存",
                save_image_action: "画像を保存",
                capturing: "キャプチャ中...",
                missing_snapshot: "スクリーンスナップショットがありません",
                missing_pin_image: "ピン留め画像のパスがありません",
                snapshot_load_failed: "スクリーンスナップショットの読み込みに失敗しました",
                pin_load_failed: "ピン留め画像の読み込みに失敗しました",
                crop_failed: "選択範囲の保存に失敗しました",
                copy_failed: "選択範囲をコピーできませんでした",
                save_failed: "選択範囲を保存できませんでした",
                pin_spawn_failed: "ピンウィンドウを開けませんでした",
                capture_title: "snap pin キャプチャ",
            },
            OverlayLanguage::Ko => Self {
                drag_hint: "드래그하여 영역 선택",
                toolbar_hint: "가장자리를 드래그하여 조정",
                pin_action: "고정",
                ocr_action: "OCR",
                close_ocr_action: "OCR 숨기기",
                rerun_ocr_action: "OCR 다시 실행",
                translate_action: "번역",
                close_action: "닫기",
                copy_action: "복사",
                copy_image_action: "이미지 복사",
                copy_selected_text_action: "선택 텍스트 복사",
                copy_all_text_action: "전체 텍스트 복사",
                save_action: "저장",
                save_image_action: "이미지 저장",
                capturing: "캡처 중...",
                missing_snapshot: "화면 스냅샷이 없습니다",
                missing_pin_image: "고정 이미지 경로가 없습니다",
                snapshot_load_failed: "화면 스냅샷을 불러오지 못했습니다",
                pin_load_failed: "고정 이미지를 불러오지 못했습니다",
                crop_failed: "선택 영역을 저장하지 못했습니다",
                copy_failed: "선택 영역을 복사하지 못했습니다",
                save_failed: "선택 영역을 저장하지 못했습니다",
                pin_spawn_failed: "고정 창을 열지 못했습니다",
                capture_title: "snap pin 캡처",
            },
            OverlayLanguage::Fr => Self {
                drag_hint: "Glissez pour selectionner une zone",
                toolbar_hint: "Glissez les bords pour ajuster",
                pin_action: "Epingler",
                ocr_action: "OCR",
                close_ocr_action: "Masquer OCR",
                rerun_ocr_action: "Relancer OCR",
                translate_action: "Traduire",
                close_action: "Fermer",
                copy_action: "Copier",
                copy_image_action: "Copier l'image",
                copy_selected_text_action: "Copier le texte selectionne",
                copy_all_text_action: "Copier tout le texte",
                save_action: "Enregistrer",
                save_image_action: "Enregistrer l'image",
                capturing: "Capture...",
                missing_snapshot: "Instantane d'ecran manquant",
                missing_pin_image: "Chemin de l'image epinglee manquant",
                snapshot_load_failed: "Echec du chargement de l'instantane",
                pin_load_failed: "Echec du chargement de l'image epinglee",
                crop_failed: "Echec de l'enregistrement de la selection",
                copy_failed: "Echec de la copie de la selection",
                save_failed: "Echec de l'enregistrement de la selection",
                pin_spawn_failed: "Echec de l'ouverture de la fenetre epinglee",
                capture_title: "capture snap pin",
            },
            OverlayLanguage::De => Self {
                drag_hint: "Ziehen, um einen Bereich auszuwahlen",
                toolbar_hint: "Kanten ziehen, um anzupassen",
                pin_action: "Anheften",
                ocr_action: "OCR",
                close_ocr_action: "OCR ausblenden",
                rerun_ocr_action: "OCR erneut",
                translate_action: "Uebersetzen",
                close_action: "Schliessen",
                copy_action: "Kopieren",
                copy_image_action: "Bild kopieren",
                copy_selected_text_action: "Ausgewaehlten Text kopieren",
                copy_all_text_action: "Gesamten Text kopieren",
                save_action: "Speichern",
                save_image_action: "Bild speichern",
                capturing: "Aufnahme...",
                missing_snapshot: "Bildschirm-Snapshot fehlt",
                missing_pin_image: "Pfad zum angehefteten Bild fehlt",
                snapshot_load_failed: "Bildschirm-Snapshot konnte nicht geladen werden",
                pin_load_failed: "Angeheftetes Bild konnte nicht geladen werden",
                crop_failed: "Auswahl konnte nicht gespeichert werden",
                copy_failed: "Auswahl konnte nicht kopiert werden",
                save_failed: "Auswahl konnte nicht gespeichert werden",
                pin_spawn_failed: "Pin-Fenster konnte nicht geoffnet werden",
                capture_title: "snap pin Aufnahme",
            },
            OverlayLanguage::ZhCn => Self {
                drag_hint: "拖拽选择截图区域",
                toolbar_hint: "拖动边缘调整选区",
                pin_action: "贴图",
                ocr_action: "OCR",
                close_ocr_action: "关闭 OCR",
                rerun_ocr_action: "重新 OCR",
                translate_action: "翻译",
                close_action: "关闭",
                copy_action: "复制",
                copy_image_action: "复制图片",
                copy_selected_text_action: "复制选中文本",
                copy_all_text_action: "复制全部文本",
                save_action: "保存",
                save_image_action: "保存图片",
                capturing: "正在截图...",
                missing_snapshot: "缺少屏幕快照",
                missing_pin_image: "缺少贴图图片路径",
                snapshot_load_failed: "屏幕快照加载失败",
                pin_load_failed: "贴图图片加载失败",
                crop_failed: "保存选区失败",
                copy_failed: "复制选区失败",
                save_failed: "保存选区失败",
                pin_spawn_failed: "打开贴图窗口失败",
                capture_title: "贴图钉截图",
            },
        }
    }
}
